function [CSI,usedNodes] = findCSI(varargin)

parameters = loadParameters;

[CSI, usedNodes] = graphSearch(varargin{1},...
                              varargin{2},...
                              parameters.alpha,...
                              parameters.wM,...
                              parameters.delColmax,...
                              parameters.delRowmax,...
                              parameters.maxJumpCol,...
                              parameters.maxJumpRow,...
                              parameters.on1,...
                              parameters.on2,...
                              parameters.on3,...
                              parameters.on4);

end

