% function testing

histogram([1 2 3]);

load('/Users/javimazzaf/Documents/work/proyectos/ophthalmology/choroidMaps/20160622/mapData.mat','descriptors');

% msk = descriptors.Age(:) > 60 & descriptors.Age(:) < 80;
msk = descriptors.Age(:) > 0;

aux    = [descriptors.AREDS_D6nasalMean(msk);...
          descriptors.AREDS_D6superiorMean(msk);...
          descriptors.AREDS_D6temporalMean(msk);...
          descriptors.AREDS_D6inferiorMean(msk);...
          descriptors.AREDS_D1Mean(msk)];
     
groups = [1 * ones(size(descriptors.AREDS_D6nasalMean(msk)));...
          2 * ones(size(descriptors.AREDS_D6superiorMean(msk)));...
          3 * ones(size(descriptors.AREDS_D6temporalMean(msk)));...
          4 * ones(size(descriptors.AREDS_D6inferiorMean(msk)));...
          5 * ones(size(descriptors.AREDS_D1Mean(msk)))];
      
fh = figure;

boxplot(aux,groups,'Symbol','')

names = {'Nasal';'Inferior';'Temporal';'Superior';'Center'};
set(gca,'FontSize',16,'XTickLabel',names)
ylim([45 355])
ylabel('CT[\mum]')

ax = gca;

ax.LineWidth = 2;

print(fh,'/Users/javimazzaf/Documents/work/proyectos/ophthalmology/choroidMaps/20160622/AREDSThickness.png','-dpng')


% aux    = [descriptors.AREDS_D3nasalMean(msk);...
%           descriptors.AREDS_D3superiorMean(msk);...
%           descriptors.AREDS_D3temporalMean(msk);...
%           descriptors.AREDS_D3inferiorMean(msk);...
%           descriptors.AREDS_D1Mean(msk)];
%      
% groups = [1 * ones(size(descriptors.AREDS_D3nasalMean(msk)));...
%           2 * ones(size(descriptors.AREDS_D3superiorMean(msk)));...
%           3 * ones(size(descriptors.AREDS_D3temporalMean(msk)));...
%           4 * ones(size(descriptors.AREDS_D3inferiorMean(msk)));...
%           5 * ones(size(descriptors.AREDS_D1Mean(msk)))];
%       
% boxplot(aux,groups)

% hist(descriptors.Age(:))